<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="My test suite" duration-ms="26" started-at="2013-01-23T14:04:38Z" finished-at="2013-01-23T14:04:38Z">
    <groups>
    </groups>
    <test name="testing" duration-ms="26" started-at="2013-01-23T14:04:38Z" finished-at="2013-01-23T14:04:38Z">
      <class name="net.sf.cram.TestCramTools">
        <test-method status="PASS" signature="test1(int)[pri:0, instance:net.sf.cram.TestCramTools@abeafe7]" name="test1" duration-ms="9" started-at="2013-01-23T14:04:38Z" finished-at="2013-01-23T14:04:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2(java.lang.String)[pri:0, instance:net.sf.cram.TestCramTools@abeafe7]" name="test2" duration-ms="2" started-at="2013-01-23T14:04:38Z" data-provider="provider" depends-on-methods="net.sf.cram.TestCramTools.test1" finished-at="2013-01-23T14:04:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[viroid.NC_003611.ill.MERGED.bwa.bam]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="FAIL" signature="test2(java.lang.String)[pri:0, instance:net.sf.cram.TestCramTools@abeafe7]" name="test2" duration-ms="1" started-at="2013-01-23T14:04:38Z" data-provider="provider" depends-on-methods="net.sf.cram.TestCramTools.test1" finished-at="2013-01-23T14:04:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[41viroids.ill.MERGED.bwa.bam]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at net.sf.cram.TestCramTools.test2(TestCramTools.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test3(java.lang.String)[pri:0, instance:net.sf.cram.TestCramTools@abeafe7]" name="test3" duration-ms="0" started-at="2013-01-23T14:04:38Z" data-provider="provider" depends-on-methods="net.sf.cram.TestCramTools.test2" finished-at="2013-01-23T14:04:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- net.sf.cram.TestCramTools -->
    </test> <!-- testing -->
  </suite> <!-- My test suite -->
</testng-results>
